Framebuffer [framebuffer_t, putpixel, fillarea]
tailix/libkernaux pull request #10
Opened 2022-01-11 21:48 UTC by ashusharmasigdev

All functions are surely working.

2022-01-12 05:28 UTC, ashusharmasigdev reviewed
Checked!

2022-01-12 06:01 UTC, kotovalexarian requested changes
First of all, thank you very much for the contribution!

Don't worry about the big number of requested changes. Most of them are more related to the code style, and I can fix them myself.

My only really important concern about this code is that it only supports one mode of framebuffer - graphical, and doesn't support text mode. While text mode is the feature of framebuffer I need mostly. Text mode is very useful for kernel debugging. And drivers in this library (console, framebuffer, maybe other in future like USB) are used mostly for debugging helpers, not as real drivers.

Can you at least add a support for mode change? We get framebuffer mode from a bootloader. Multiboot 2 and Stivale 2 boot protocols provide information about the mode. See `include/kernaux/multiboot2.h` for Multiboot 2 framebuffer info tag:

https://github.com/tailix/libkernaux/blob/5296e9cce3419f122a8ed72abdb4e0eb79dac2e9/include/kernaux/multiboot2.h#L136-L149

2022-01-12 17:05 UTC, ashusharmasigdev commented
**Namaste** , I done the code as per your indications, this is my first contribution, so....
One more thing, I don't used much EGA or VGA , so some bugs can alive, maybe you need to fix those or i will in feature.
I uses C++ and Classes, so those are bit confused me in C.

2022-01-13 05:51 UTC, kotovalexarian commented
@ashusharmasigdev, please give me access to your repo so I can edit the code before merge.

2022-01-13 08:49 UTC, ashusharmasigdev commented
Access Granted.

2022-01-13 10:10 UTC, kotovalexarian commented
I've fixed coding style, but text mode is still required. I'll add it later or you can do it youself.

2022-01-13 10:11 UTC, kotovalexarian commented on src/framebuffer.c
> +    return (framebuffer_t){
Maybe more checks are needed.

2022-01-14 07:28 UTC, kotovalexarian commented
@ashusharmasigdev Stivale 2 parser feature should be added in separate pull request.

2022-01-14 08:25 UTC, ashusharmasigdev commented
@kotovalexarian What about adding a Basic VGA Font header file, to put it on framebuffer?

2022-01-14 08:39 UTC, kotovalexarian commented
> @kotovalexarian What about adding a Basic VGA Font header file, to put it on framebuffer?

Let's finish the framebuffer itself first.

2022-12-03 10:50 UTC, kotovalexarian commented
Hello again. I decided to remove drivers from **libkernaux** (#127) and create a new repository for them (have not created yet). Therefore I'm closing this PR. I'll write a driver for framebuffer later. This still isn't a priority because I use serial console for I/O in my projects, it's enough for development and testing.

2022-12-03 10:50 UTC, closed without merging

2022-12-04 03:39 UTC, ashusharmasigdev commented
Hello to you also, i currently can't continue my OS developments i am busy on some private web projects, i may continue later on,, this was the reason i can't contribute the libkernaux development. Do whatever your planing is. I may continue it later on.
Thanks.

2022-12-04 10:51 UTC, kotovalexarian commented
Drivers will be here: https://github.com/tailix/drivers